// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbsyvufzvyzpbxwkhstr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic3l2dWZ6dnl6cGJ4d2toc3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDcxMTEsImV4cCI6MjA2ODI4MzExMX0.a7MhIyJvl4Y_7UxAUe5KcF_gMO8srI6CEA7MupAzAIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});