// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulsytshozpwljumgfpro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsc3l0c2hvenB3bGp1bWdmcHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTcwMDgsImV4cCI6MjA2ODI5MzAwOH0.JKKofLuO7oksr9byei6fhttXIBYtTEKYjh2pwuzJfoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});